package ebmsapp.entities;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name="bill"
    ,catalog="ebms_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="bill_number") 
)
public class Bill  implements java.io.Serializable {


     private Integer idbill;
     private Client client;
     private String billNumber;
     private double amount;
     private Date dueDate;
     private Date billDate;
     private int unitConsumed;
     private String process;

    public Bill() {
    }

    public Bill(Client client, String billNumber, double amount, Date dueDate, Date billDate, int unitConsumed, String process) {
       this.client = client;
       this.billNumber = billNumber;
       this.amount = amount;
       this.dueDate = dueDate;
       this.billDate = billDate;
       this.unitConsumed = unitConsumed;
       this.process = process;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idbill", unique=true, nullable=false)
    public Integer getIdbill() {
        return this.idbill;
    }
    
    public void setIdbill(Integer idbill) {
        this.idbill = idbill;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    
    @Column(name="bill_number", unique=true, nullable=false, length=45)
    public String getBillNumber() {
        return this.billNumber;
    }
    
    public void setBillNumber(String billNumber) {
        this.billNumber = billNumber;
    }

    
    @Column(name="Amount", nullable=false, precision=22, scale=0)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="due_date", nullable=false, length=10)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bill_date", nullable=false, length=10)
    public Date getBillDate() {
        return this.billDate;
    }
    
    public void setBillDate(Date billDate) {
        this.billDate = billDate;
    }

    
    @Column(name="unit_consumed", nullable=false)
    public int getUnitConsumed() {
        return this.unitConsumed;
    }
    
    public void setUnitConsumed(int unitConsumed) {
        this.unitConsumed = unitConsumed;
    }

    
    @Column(name="process", nullable=false, length=6)
    public String getProcess() {
        return this.process;
    }
    
    public void setProcess(String process) {
        this.process = process;
    }




}


