package ebmsapp.entities;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="ebms_db"
)
public class Client  implements java.io.Serializable {


     private Integer idclient;
     private Cities cities;
     private String firstname;
     private String lastname;
     private Date birthdate;
     private String profession;
     private String email;
     private String gender;
     private String phonenumber;
     private String username;
     private String address;
     private String pobox;
     private String picture;
     private Set consumptions = new HashSet(0);
     private Set contracts = new HashSet(0);
     private Set bills = new HashSet(0);

    public Client() {
    }

	
    public Client(Cities cities, String firstname, String profession, String gender, String phonenumber, String username, String address) {
        this.cities = cities;
        this.firstname = firstname;
        this.profession = profession;
        this.gender = gender;
        this.phonenumber = phonenumber;
        this.username = username;
        this.address = address;
    }
    public Client(Cities cities, String firstname, String lastname, Date birthdate, String profession, String email, String gender, String phonenumber, String username, String address, String pobox, String picture, Set consumptions, Set contracts, Set bills) {
       this.cities = cities;
       this.firstname = firstname;
       this.lastname = lastname;
       this.birthdate = birthdate;
       this.profession = profession;
       this.email = email;
       this.gender = gender;
       this.phonenumber = phonenumber;
       this.username = username;
       this.address = address;
       this.pobox = pobox;
       this.picture = picture;
       this.consumptions = consumptions;
       this.contracts = contracts;
       this.bills = bills;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idclient", unique=true, nullable=false)
    public Integer getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(Integer idclient) {
        this.idclient = idclient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cities_id", nullable=false)
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }

    
    @Column(name="firstname", nullable=false, length=45)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname", length=45)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthdate", length=10)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="profession", nullable=false, length=45)
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="gender", nullable=false, length=6)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="phonenumber", nullable=false, length=45)
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="address", nullable=false, length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="pobox", length=45)
    public String getPobox() {
        return this.pobox;
    }
    
    public void setPobox(String pobox) {
        this.pobox = pobox;
    }

    
    @Column(name="picture", length=45)
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set getConsumptions() {
        return this.consumptions;
    }
    
    public void setConsumptions(Set consumptions) {
        this.consumptions = consumptions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set getContracts() {
        return this.contracts;
    }
    
    public void setContracts(Set contracts) {
        this.contracts = contracts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set getBills() {
        return this.bills;
    }
    
    public void setBills(Set bills) {
        this.bills = bills;
    }




}


