package ebmsapp.entities;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consumption generated by hbm2java
 */
@Entity
@Table(name="consumption"
    ,catalog="ebms_db"
)
public class Consumption  implements java.io.Serializable {


     private Integer idconsumption;
     private Client client;
     private Date date;
     private int previousConsumed;
     private int consumed;

    public Consumption() {
    }

    public Consumption(Client client, Date date, int previousConsumed, int consumed) {
       this.client = client;
       this.date = date;
       this.previousConsumed = previousConsumed;
       this.consumed = consumed;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idconsumption", unique=true, nullable=false)
    public Integer getIdconsumption() {
        return this.idconsumption;
    }
    
    public void setIdconsumption(Integer idconsumption) {
        this.idconsumption = idconsumption;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="previous_consumed", nullable=false)
    public int getPreviousConsumed() {
        return this.previousConsumed;
    }
    
    public void setPreviousConsumed(int previousConsumed) {
        this.previousConsumed = previousConsumed;
    }

    
    @Column(name="consumed", nullable=false)
    public int getConsumed() {
        return this.consumed;
    }
    
    public void setConsumed(int consumed) {
        this.consumed = consumed;
    }




}


