package ebmsapp.entities;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name="contract"
    ,catalog="ebms_db"
)
public class Contract  implements java.io.Serializable {


     private Integer idcontract;
     private Client client;
     private String contractNumber;
     private Date contractDate;
     private String clientCategorie;
     private Float meterNumber;

    public Contract() {
    }

	
    public Contract(Client client) {
        this.client = client;
    }
    public Contract(Client client, String contractNumber, Date contractDate, String clientCategorie, Float meterNumber) {
       this.client = client;
       this.contractNumber = contractNumber;
       this.contractDate = contractDate;
       this.clientCategorie = clientCategorie;
       this.meterNumber = meterNumber;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcontract", unique=true, nullable=false)
    public Integer getIdcontract() {
        return this.idcontract;
    }
    
    public void setIdcontract(Integer idcontract) {
        this.idcontract = idcontract;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    
    @Column(name="contract_number", length=45)
    public String getContractNumber() {
        return this.contractNumber;
    }
    
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="contract_date", length=10)
    public Date getContractDate() {
        return this.contractDate;
    }
    
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    
    @Column(name="client_categorie", length=45)
    public String getClientCategorie() {
        return this.clientCategorie;
    }
    
    public void setClientCategorie(String clientCategorie) {
        this.clientCategorie = clientCategorie;
    }

    
    @Column(name="meter_number", precision=12, scale=0)
    public Float getMeterNumber() {
        return this.meterNumber;
    }
    
    public void setMeterNumber(Float meterNumber) {
        this.meterNumber = meterNumber;
    }




}


